### ISSUE TITLE
Hexdropper Tutorial: Example for read_image() function

### ISSUE THREAD

**Issue by juliaeveritt** [UBC-MDS/hexdropper#31]
Demonstrate how to use read_image function. Plan to use image of MDS logo.

**Comment by monazhu** [comment]
Hey @juliaeveritt, I managed to fix the issue you were experiencing earlier. I think it's the way the package is imported - the format that works is `from hexdropper.read_image import read_image` rather than `from hexdropper import read_image`. I think it we want to import `hexdropper` as a package like how we normally do it, we would have to change the namespace in `__init__.py`, but what we have should work :)

**Comment by monazhu** [comment]
Oh actually I just noticed that you've pushed another PR through with the fixes 😂. I'll pull the changes through and update my section accordingly!

**Comment by monazhu** [comment]
Checked over section in `example.ipynb` - will close and mark task as completed!
