### ISSUE TITLE
Hexdropper Tutorial: Example for create_color_image() function

### ISSUE THREAD

**Issue by hchqin** [UBC-MDS/hexdropper#35]
Demonstrate the use of create_color_image() if the user wants to export an image for the given hex code., or the user can use the given hex code to create the plot for visualization

**Comment by hchqin** [comment]
Please refer to commit 1272c66fc8f1a94eab3b31b06fd1605de852c5ec and pull request #42

**Comment by monazhu** [comment]
Checked over section in `example.ipynb` - will close and mark task as completed!

**Comment by joeywwwu** [comment]
@hchqin Hey Hancheng, I noted that there are two errors with the create_color_image() function on my side, they are issue with # symbol. I kind of understand this function is used for saving image, which has no output figure right below the codes, so it should not be a big deal. However, I'm not sure how it will be displayed on readthedoc since I'm still working on it, so I reopened this issue in case it also happens in readthedoc. Thanks!

<img width="962" alt="image" src="https://github.com/UBC-MDS/hexdropper/assets/143630759/731c97af-31f3-4019-9f65-a0705d9d2a9e">

**Comment by hchqin** [comment]
Hi @joeywwwu, I believe the issue you encountered is due to the create_color_image function originally being designed to accept a hex code without the '#' symbol. To address this, I have updated the function to now accept hex codes with the '#' included. Please see the changes in commit 0b029f15d24f8d06d2143616a937d19531c87f8e for the details.
