### ISSUE TITLE
Update License

### ISSUE THREAD

**Issue by monazhu** [UBC-MDS/hexdropper#58]
Review current license for the project and update as necessary.

**Comment by monazhu** [comment]
@joeywwwu @hchqin @juliaeveritt I realized that we never actually ended up discussing whether we needed to update/change our license or not. Personally, I do think that the MIT license suits our needs since it's relatively flexible and favours permissibility, but I also don't have a strong preference (say between MIT vs GNU or other licenses). What do you guys think?

**Comment by joeywwwu** [comment]
@monazhu Thanks for bringing this up! I don't have a strong preference either. I think MIT license works well in our project because it only requires the license and copyright notice be included with the package, and could allow for broad reuse of our package when compared with other more restrictive licenses, such as GNU

**Comment by juliaeveritt** [comment]
Agreed! MIT seems like a good fit to me too. Thanks for remembering this!

**Comment by hchqin** [comment]
One thing that MIT license might be problematic is that it provides no warranty or liability protection, and could have legal risk if our package is used in critical applications. On the other hand, since our package is just hex-dropping color from a given image, I think this shouldn't be a serious concern?

**Comment by monazhu** [comment]
Okay sounds good! Then we'll stick with the MIT license we currently have :)
